"Error","catalina-exec-3","03/23/19","20:57:06",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-3","03/23/19","20:57:10",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-10","03/23/19","20:59:45",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-10","03/23/19","20:59:49",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-10","03/23/19","21:00:10",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-10","03/23/19","21:00:14",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-1","03/23/19","21:07:30",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-1","03/23/19","21:07:34",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-12","03/23/19","21:08:15",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-12","03/23/19","21:08:19",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-10","03/23/19","21:08:47",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1013)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2238)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2159)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3597)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3529)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:935)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4101)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1300)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2337)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2177)
	... 13 more
"Error","catalina-exec-3","03/23/19","21:13:08",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-3","03/23/19","21:13:08",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-3","03/23/19","21:13:32",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'cw3'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'cw3'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-3","03/23/19","21:13:32",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'cw3'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'cw3'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-13","03/23/19","21:14:42",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-13","03/23/19","21:14:42",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-10","03/23/19","21:18:43",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-10","03/23/19","21:18:46",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-10","03/23/19","21:19:00",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-10","03/23/19","21:19:00",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-13","03/23/19","21:20:41",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-13","03/23/19","21:20:41",,"[Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version."
java.sql.SQLException: [Macromedia][MySQL JDBC Driver]Connections to MySQL Community Server are not supported. Please contact MySQL to obtain a MySQL Enterprise or Commercial version.
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.az(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-13","03/23/19","21:21:01",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-13","03/23/19","21:21:01",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-3","03/23/19","21:43:44",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-3","03/23/19","21:43:44",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-3","03/23/19","21:43:52",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-4","03/23/19","21:48:56",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-4","03/23/19","21:48:56",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","21:52:54",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","21:52:54",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:04:07",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:04:07",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:04:26",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:04:26",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:12:03",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:12:03",,"[Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)"
java.sql.SQLInvalidAuthorizationSpecException: [Macromedia][MySQL JDBC Driver][MySQL]Access denied for user 'root'@'localhost' (using password: YES)
	at macromedia.jdbc.mysqlbase.ddb9.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb9.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.ddb8.a(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.a(Unknown Source)
	at macromedia.jdbc.mysql.sio.dda.g(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.aw(Unknown Source)
	at macromedia.jdbc.mysql.MySQLImplConnection.d(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.k(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.b(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseConnection.a(Unknown Source)
	at macromedia.jdbc.mysqlbase.BaseDriver.connect(Unknown Source)
	at macromedia.jdbc.MacromediaDriver.connect(Unknown Source)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
"Error","catalina-exec-5","03/23/19","22:15:55",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-5","03/23/19","22:15:59",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-3","03/23/19","22:19:17",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-3","03/23/19","22:19:21",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-6","03/23/19","22:35:59",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-5","03/23/19","22:40:48",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-5","03/23/19","22:40:52",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-4","03/23/19","22:44:02",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'cw3'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-3","03/23/19","22:44:38",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-3","03/23/19","22:44:42",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-6","03/24/19","08:38:47",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-7","03/24/19","08:41:46",,"Could not create connection to database server. Attempted reconnect 3 times. Giving up."
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:919)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2105)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2030)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:778)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at coldfusion.server.j2ee.sql.pool.JDBCPool.createPhysicalConnection(JDBCPool.java:614)
	at coldfusion.server.j2ee.sql.pool.ConnectionRunner$RunnableConnection.run(ConnectionRunner.java:67)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:871)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1714)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1224)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2199)
	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2046)
	... 13 more
"Error","catalina-exec-2","03/24/19","08:44:05","cfadmin","Element UPDATES is undefined in SESSION. The specific sequence of files included or processed is: C:\ColdFusion10\cfusion\wwwroot\CFIDE\administrator\updates\installer_input.cfm, line: 33 "
coldfusion.runtime.UndefinedElementException: Element UPDATES is undefined in SESSION.
	at coldfusion.runtime.CfJspPage.resolveCanonicalName(CfJspPage.java:1752)
	at coldfusion.runtime.CfJspPage._resolve(CfJspPage.java:1705)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1854)
	at coldfusion.runtime.CfJspPage._resolveAndAutoscalarize(CfJspPage.java:1833)
	at cfinstaller_input2ecfm1277900361.runPage(C:\work\cf10_updates\cfusion\wwwroot\CFIDE\administrator\updates\installer_input.cfm:33)
	at coldfusion.runtime.CfJspPage.invoke(CfJspPage.java:244)
	at coldfusion.tagext.lang.IncludeTag.doStartTag(IncludeTag.java:444)
	at coldfusion.filter.CfincludeFilter.invoke(CfincludeFilter.java:65)
	at coldfusion.filter.IpFilter.invoke(IpFilter.java:64)
	at coldfusion.filter.ApplicationFilter.invoke(ApplicationFilter.java:443)
	at coldfusion.filter.RequestMonitorFilter.invoke(RequestMonitorFilter.java:48)
	at coldfusion.filter.MonitoringFilter.invoke(MonitoringFilter.java:40)
	at coldfusion.filter.PathFilter.invoke(PathFilter.java:112)
	at coldfusion.filter.LicenseFilter.invoke(LicenseFilter.java:30)
	at coldfusion.filter.ExceptionFilter.invoke(ExceptionFilter.java:94)
	at coldfusion.filter.ClientScopePersistenceFilter.invoke(ClientScopePersistenceFilter.java:28)
	at coldfusion.filter.BrowserFilter.invoke(BrowserFilter.java:38)
	at coldfusion.filter.NoCacheFilter.invoke(NoCacheFilter.java:46)
	at coldfusion.filter.GlobalsFilter.invoke(GlobalsFilter.java:38)
	at coldfusion.filter.DatasourceFilter.invoke(DatasourceFilter.java:22)
	at coldfusion.filter.CachingFilter.invoke(CachingFilter.java:62)
	at coldfusion.CfmServlet.service(CfmServlet.java:204)
	at coldfusion.bootstrap.BootstrapServlet.service(BootstrapServlet.java:89)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at coldfusion.monitor.event.MonitoringServletFilter.doFilter(MonitoringServletFilter.java:42)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at coldfusion.filter.ClickjackingProtectionFilter.doFilter(ClickjackingProtectionFilter.java:75)
	at coldfusion.bootstrap.BootstrapFilter.doFilter(BootstrapFilter.java:46)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:928)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:414)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:539)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
